spring.application.name=booking_system
# Local database configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
# spring.datasource.username=postgres
# spring.datasource.password=1234

# Aiven cloud database configuration
spring.datasource.url=jdbc:postgresql://campus-book-db-fridayampomah-4891.i.aivencloud.com:28366/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD:your_password_here}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.prefix=file:../frontend/templates/
spring.web.resources.static-locations=file:../frontend/static/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
